name: actions_pipeline
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:   
       run:
        working-directory: ./main
        
    steps:

        -  run: terraform init
        -  run: terraform workspace new dev
        -  run: terraform plan -out=tfdev_plan -var "env=dev" -var "project_id=resolute-vault-339210" -var "function-name=function-dev" 
