name: actions_pipeline

on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
        
    steps:

        -  run: python3 test_gcloudstorage.py
        -  run: terraform workspace new dev
        -  run: terraform plan -out=tfdev_plan -var "env=dev" -var "project_id=resolute-vault-339210" -var "function-name=function-dev" 
