name: actions_pipeline
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      -  run: gcloud auth activate-service-account --key-file resolute-vault-339210-0935f51f162f.json
      -  run: python3 test_gcloudstorage.py
